/*
 * ServicioConsumible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Solicitud
 */
public class SolicitudTest {
    private final Solicitud model = new Solicitud();

    /**
     * Model tests for Solicitud
     */
    @Test
    public void testSolicitud() {
        // TODO: test Solicitud
    }

    /**
     * Test the property 'cantidadesIniciales'
     */
    @Test
    public void cantidadesInicialesTest() {
        // TODO: test cantidadesIniciales
    }

    /**
     * Test the property 'nombreEntidades'
     */
    @Test
    public void nombreEntidadesTest() {
        // TODO: test nombreEntidades
    }

}
