/*
 * ServicioConsumible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.EmailResponse;
import org.openapitools.client.model.ProblemDetails;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmailApi
 */
@Disabled
public class EmailApiTest {

    private final EmailApi api = new EmailApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void emailPostTest() throws ApiException {
        String emailAddress = null;
        String message = null;
        EmailResponse response = api.emailPost(emailAddress, message);
        // TODO: test validations
    }

}
