/*
 * ServicioConsumible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ProblemDetails;
import org.openapitools.client.model.Solicitud;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SolicitudApi
 */
@Disabled
public class SolicitudApiTest {

    private final SolicitudApi api = new SolicitudApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void solicitudComprobarSolicitudGetTest() throws ApiException {
        String nombreUsuario = null;
        Integer tok = null;
        List<Integer> response = api.solicitudComprobarSolicitudGet(nombreUsuario, tok);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void solicitudGetSolicitudesUsuarioGetTest() throws ApiException {
        String nombreUsuario = null;
        List<Integer> response = api.solicitudGetSolicitudesUsuarioGet(nombreUsuario);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void solicitudSolicitarPostTest() throws ApiException {
        String nombreUsuario = null;
        Solicitud solicitud = null;
        Object response = api.solicitudSolicitarPost(nombreUsuario, solicitud);
        // TODO: test validations
    }

}
